server:
  port: 8000

spring:
  application:
    name: customer-apigateway-service
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    enabled: true
#  sleuth:
#    sampler:
#      probability: 1.0
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true

      routes:
        - id: order-service
          uri: http://order-service.default.svc.cluster.local:9200
          predicates:
            - Path=/order-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/order-service/(?<segment>.*),/$\{segment}

        - id: store-service
          uri: http://store-service.default.svc.cluster.local:9300
          predicates:
            - Path=/store-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/store-service/(?<segment>.*),/$\{segment}

        - id: notification-service
          uri: http://notification-service.default.svc.cluster.local:9100
          predicates:
            - Path=/notification-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/notification-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: http://user-service.default.svc.cluster.local:9000
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:9000
          predicates:
            - Path=/user-service/reissue
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:9000
          predicates:
            - Path=/user-service/logout
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:9000
          predicates:
            - Path=/user-service/auth/reissue
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:9000
          predicates:
            - Path=/user-service/oauth2/authorization/*
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:9000
          predicates:
            - Path=/user-service/*/oauth2/code/*
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}
        - id: user-service
          uri: http://user-service.default.svc.cluster.local:9000
          predicates:
            - Path=/user-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

token:
  access-expired-time: 3600000
  refresh-expired-time: 604800000
  secret: Y2h1bmdqbTA3MTEtbXNhLXNwcmluZy1jbG91ZC1qYWltZS1qYW5nd29uLXNlby1zb29uZ3NpbC11bml2LWdyYWR1YXRpb24tc3ByaW5nLWJvb3Qtand0LWtleQo=
  refresh-token-name: refresh-token
  access-token-name: access-token
